---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend-service-name }}
spec:
  ports:
  - name: http
    port: {{ .Values.internal-service.port }} #80
    targetPort: 8080
  selector:
    app: {{ .Values.frontend-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.internal-service.type }} #ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend-service-name }}-{{ .Release.Revision }}-external
spec:
  ports:
  - name: http
    port: {{ .Values.external-service.port }} #80
    targetPort: 8080
  selector:
    app: {{ .Values.frontend-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.external-service.type }} #LoadBalancer
