---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend_service_name }}
spec:
  ports:
  - name: http
    port: {{ .Values.internal_service.port }} #80
    targetPort: 8080
  selector:
    app: {{ .Values.frontend_service_name }}-{{ .Release.Revision }}
  type: {{ .Values.internal_service.type }} #ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend_service_name }}-external
spec:
  ports:
  - name: http
    port: {{ .Values.external_service.port }} #80
    targetPort: 8080
  selector:
    app: {{ .Values.frontend_service_name }}-{{ .Release.Revision }}
  type: {{ .Values.external_service.type }} #LoadBalancer
