---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shipping-service-name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #50051
    targetPort: 50051
  selector:
    app: {{ .Values.shipping-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }} #ClusterIP