---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cart_service_name }}-{{ .Release.Revision }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cart_service_name }}-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: {{ .Values.cart_service_name }}-{{ .Release.Revision }}
    spec:
      containers:
      - env:
        - name: SPANNER_CONNECTION_STRING
          value: {{ .Values.spanner_connection_string }}
        image: {{ .Values.cart_service_image }}
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7070
            - -rpc-timeout=5s
          initialDelaySeconds: 15
          periodSeconds: 10
        name: server
        ports:
        - containerPort: 7070
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:7070
            - -rpc-timeout=5s
          initialDelaySeconds: 15
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ .Values.cart_service_name }}
      terminationGracePeriodSeconds: 5