---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cart_service_name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #7070
    targetPort: 7070
  selector:
    app: {{ .Values.cart_service_name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }} #ClusterIP