---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.checkout-service-name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #5050
    targetPort: 5050
  selector:
    app: {{ .Values.checkout-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }} #ClusterIP