---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.product-catalog-service-name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #3550
    targetPort: 3550
  selector:
    app: {{ .Values.product-catalog-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }}  #ClusterIP