# AD SERVICE
ad-service-name: adservice
ad-service-image: gcr.io/google-samples/microservices-demo/adservice:v0.6.0

# CART SERVICE
cart-service-name: cartservice
cart-service-image: gcr.io/google-samples/microservices-demo/cartservice:v0.6.0
spanner-connection-string: "projects/${SPANNER_PROJECT}/instances/${SPANNER_INSTANCE}/databases/${SPANNER_DATABASE}"
spanner-db-user-sa: "spanner-db-user-sa@qwiklabs-gcp-04-5dc03957119b.iam.gserviceaccount.com"

# CHECKOUT SERVICE
checkout-service-name: checkoutservice
checkout-service-image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.6.0

# CURRENCY SERVICE
currency-service-name: currencyservice
currency-service-image: gcr.io/google-samples/microservices-demo/currencyservice:v0.6.0

# EMAIL SERVICE
email-service-name: emailservice
email-service-image: gcr.io/google-samples/microservices-demo/emailservice:v0.6.0

# FRONTEND
frontend-service-name: frontend
frontend-service-image: frontend_image

# PAYMENT
payment-service-name: paymentservice
payment-service-image: gcr.io/google-samples/microservices-demo/paymentservice:v0.6.0

# PRODUCT CATALOG
product-catalog-service-name: productcatalogservice
product-catalog-service-image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.6.0

# RECOMMENDATION
recommendation-service-name: recommendationservice
recommendation-service-image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.6.0

# SHIPPING
shipping-service-name: shippingservice
shipping-service-image:  gcr.io/google-samples/microservices-demo/shippingservice:v0.6.0



