---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.email-service-name }}-{{ .Release.Revision }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.email-service-name }}-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: {{ .Values.email-service-name }}-{{ .Release.Revision }}
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        image: {{ .Values.email-service-image }}
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:8080
          periodSeconds: 5
        name: server
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:8080
          periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ .Values.email-service-name }}-{{ .Release.Revision }}
      terminationGracePeriodSeconds: 5