---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.email_service_name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #5000
    targetPort: 8080
  selector:
    app: {{ .Values.email_service_name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }} #ClusterIP