apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  namespace: default
  name: frontend-pod-mon
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: metrics-port
    path: /metrics
    interval: 30s
