---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.currency-service-name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #7000
    targetPort: 7000
  selector:
    app: {{ .Values.currency-service-name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }} #ClusterIP