name: Application CD
on:
  workflow_dispatch: 

jobs:
  Deploy-Application:
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        workflow: app_ci.yaml
        github_token: ${{ github.token }}
        repo: ${{ github.repository }}
        name: Artifacts
        path: Artifacts

    - name: List Content
      run: |
          cd Application Artifacts
          ls 
          