name: Application CD
on:
  workflow_dispatch: 

jobs:
  # Build-Application:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Download Artifacts
  #     uses: dawidd6/action-download-artifact@v8
  #     with:
  #       workflow: app_ci.yaml
  #       github_token: ${{ github.token }}
  #       repo: ${{ github.repository }}
  #       name: Application Artifacts
  #       path: Application Artifacts

  #   - name: List Content
  #     run: |
  #         cd Application Artifacts
  #         ls 

  Download-Artifacts:
    name: 'Download Artifacts'
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        workflow: app_ci.yaml
        github_token: ${{ github.token }}
        repo: ${{ github.repository }}
        name: Application-Artifacts
        path: Application-Artifacts

    - name: List Content
      run: |
          pwd
          ls    

  Build-Application:
    name: 'Build Application'
    needs: Download-Artifacts
    runs-on: ubuntu-latest
    steps:
    - name: List Content
      run: |
          ls 
          cd Application-Artifacts
    
    - name: Docker Version
      run: |
          docker --version

    - name: Docker Build
      run: |
          cd Application-Artifacts/Application/bank-of-anthos/src/frontend/Dockerfile
          docker build --t . 
