name: Application CI 
on:
  push:
    branches: 
      - dev
    paths: 
      - Application
      - .github/workflows/app_ci.yaml
jobs:
  Application-Artifact:
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/3-Tier-GKE-SQL/3-Tier-GKE-SQL/Application
    steps:
      - uses: actions/checkout@v3
      - name: Echo
        run: echo "Creating artifact"
        
      - uses: actions/upload-artifact@main
        name: Uploading Application Artifact
        with:
          name: Application Artifacts
          path: ./*