name: Frontend Service Deploy
on:
  workflow_dispatch:

jobs:
  Deploy-Application:
    name: 'Deploy Frontend Service'
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        workflow: frontend_ci.yaml
        github_token: ${{ github.token }}
        repo: ${{ github.repository }}
        name: Application-Artifacts
        path: Application-Artifacts
    
    - name: Install Helm
      run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y 
          helm version
    
    # # Setup gcloud CLI
    # - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
    #   with:
    #     service_account_key: ${{ secrets.GKE_SA_KEY }}
    #     project_id: ${{ vars.PROJECT_ID }}
    
    # # Get the GKE credentials so we can deploy to the cluster
    # - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
    #   with:
    #     cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
    #     location: ${{ vars.GKE_ZONE }}
    #     credentials: ${{ secrets.GKE_SA_KEY }}

    # - name: Deploy Frontend Application
    #   run: |
    #      helm install frontend --debug --dry-run Application-Artifacts/Helm-Charts/frontend
