name: Frontend Deploy
on:
  workflow_dispatch:

jobs:
  Deploy-Application:
    name: 'Deploy Frontend Service'
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: dawidd6/action-download-artifact@v8
      with:
        workflow: app_ci.yaml
        github_token: ${{ github.token }}
        repo: ${{ github.repository }}
        name: Application-Artifacts
        path: Application-Artifacts

    - name: Change Directory
      run: |
          ls 
          cd Application-Artifacts
          ls
          cd Helm-Charts
          ls
    
    - name: Install Helm
      run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm -y 
          helm version

    - name: Deploy Frontend Application
      run: |
         helm install frontend --debug --dry-run frontend
