name: Helm Build
on:
  workflow_dispatch:
  push:
    branches: 
      - Dev
      - Test
      - Prod
    paths: 
      - Application/Helm-Charts/*
      - .github/workflows/helm_ci.yaml

jobs:
  Helm-Build: 
    name: 'Helm Artifact'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/3-tier-GKE-Spanner/3-tier-GKE-Spanner/Application

    steps:
            
      - name: Checkout
        uses: actions/checkout@v2

      - name: Creating artifact
        run: echo "Creating artifact"
        
      - uses: actions/upload-artifact@main
        name: Uploading Application Artifact
        with:
          name: Application-Artifacts
          path: ${{ github.workspace }}/Application/*          
