name: Infrastructure CI 
on:
  push:
    branches: 
      - dev
    paths: 
      - Infrastructure
      - .github/workflows/infra_ci.yaml
jobs:
  Infrastructure-Artifact:
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/3-tier-GKE-SQL/3-tier-GKE-SQL/Infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: List Content
        run: |
            ls 
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - uses: actions/checkout@v3
      - name: Echo
        run: echo "Creating artifact"
        
      - uses: actions/upload-artifact@main
        name: Uploading Infrastructure Artifact
        with:
          name: Infrastructure-Artifacts
          path: ./*