name: 'Infrastructure CD'
on:
  workflow_dispatch:
    inputs:
      project_env:
        description: "Project Env - Dev, Test, Prod"
        required: True

env:
    project_env: ${{ inputs.project_env }}

jobs:   
  Terraform-Plan:
    runs-on: ubuntu-latest
    steps:    
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts/Env/${{ inputs.project_env }}
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init -backend=false

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 

  Dev-Deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.project_env }} == 'Dev'
    needs: Terraform-Plan
    environment:
     name: Dev_Env
     url: https://github.com
    steps: 
      - name: Deployment Environment
        run: echo "Dev Env Deployment"
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts/Env/${{ inputs.project_env }}
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init -backend=false

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}     

  Test-Deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.project_env }} == 'Test'
    needs: Terraform-Plan
    environment:
     name: Test_Env
     url: https://github.com
    steps: 
      - name: Deployment Environment
        run: echo "Dev Env Deployment"
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts/Env/${{ inputs.project_env }}
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init -backend=false

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}   

  Prod-Deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.project_env }} == 'Prod'
    needs: Terraform-Plan
    environment:
     name: Prod_Env
     url: https://github.com
    steps: 
      - name: Deployment Environment
        run: echo "Dev Env Deployment"
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts/Env/${{ inputs.project_env }}
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init -backend=false

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}   