name: 'Infrastructure CD'
on:
 workflow_dispatch:

jobs:     
  terraform:
    name: 'Terraform INFRA'
    runs-on: ubuntu-latest
    steps:

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 
