name: 'Infrastructure CD'
on:
 workflow_dispatch:

jobs:   
  terraform1:
    name: 'Terraform Bootstrap'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: /home/runner/work/3-tier-GKE-Spanner/3-tier-GKE-Spanner/Infrastructure/Bootstrap

    steps:

    - name: Checkout
      uses: actions/checkout@v2 
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
  
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Fmt
      run: terraform fmt
        
    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        
    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
          
  terraform2:
    name: 'Terraform INFRA'
    runs-on: ubuntu-latest
    steps:

      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: infra_ci.yaml
          github_token: ${{ github.token }}
          repo: ${{ github.repository }}
          name: Infrastructure-Artifacts
          path: Infrastructure-Artifacts

      - name: List Content
        run: |
            ls 
            cd ./Infrastructure-Artifacts
            ls
     
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Validate
      #   run: terraform validate

      # - name: Terraform Plan
      #   id: plan
      #   run: terraform plan 

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   env:
      #     GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }} 
