name: Generate terraform docs
on:
  push:
    branches: 
      - dev
jobs:
  Docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the TF_README.md
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ./Infrastructure/Env/Dev,./Infrastructure/Env/Prod,./Infrastructure/modules
        output-file: TF_README.md
        output-method: inject
        git-push: "true"