name: Generate terraform docs
on:
  workflow_dispatch:
  push:
    branches: 
      - Dev
      - Test 
      - Prod
    paths:
      - ./Infrastructure
      - .github/workflows/readme.yaml
jobs:
  Dev_Readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the ./Infrastructure/Env/Dev/TF_README.md
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ./Infrastructure/Env/Dev
        output-file: TF_README.md
        output-method: inject
        git-push: "true"

  Test_Readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the ./Infrastructure/Env/Test/TF_README.md
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ./Infrastructure/Env/Test
        output-file: TF_README.md
        output-method: inject
        git-push: "true"

  Prod_Readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the ./Infrastructure/Env/Dev/TF_README.md
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ./Infrastructure/Env/Prod
        output-file: TF_README.md
        output-method: inject
        git-push: "true"
