---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ad_service_name }}-{{ .Release.Revision }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.ad_service_name }}-{{ .Release.Revision }}
  template:
    metadata:
      labels:
        app: {{ .Values.ad_service_name }}-{{ .Release.Revision }}
    spec:
      containers:
      - env:
        - name: PORT
          value: "9555"
        image: {{ .Values.ad_service_image }} 
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9555
          initialDelaySeconds: 20
          periodSeconds: 15
        name: server
        ports:
        - containerPort: 9555
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:9555
          initialDelaySeconds: 20
          periodSeconds: 15
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 200m
            memory: 180Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: {{ .Values.ad_service_name }}
      terminationGracePeriodSeconds: 5