---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ad_service_name }}
spec:
  ports:
  - name: grpc
    port: {{ .Values.service.port }} #9555
    targetPort: 9555
  selector:
    app: {{ .Values.ad_service_name }}-{{ .Release.Revision }}
  type: {{ .Values.service.type }}
  # ClusterIP